### PR TITLE
Add sender id to sms message

### PR DESCRIPTION
**Pull request by elifipekuysal**

### CODE REVIEW

**Comment by PandasProperty** [comment]
@adohertyTS I saw you are active in recent issues. What is the status of this PR?  can it be merged? I need the sender id for my app :(

**Comment by elifipekuysal** [comment]
> @elifipekuysal when will this branch be merged into master?

@PandasProperty 1 year passed since I've opened this PR, so I think this project is not maintaining. I solved my issue by creating necessary classes in my project and adding sender id to there. I suggest you do the same. If you'll need any help, you can always reach out to me!

**Comment by adohertyTS** [comment]
Regarding this pull request, we do not currently accept external pull requests for our SDKs. But I will talk with our product team to see if I can get a little more information to help you with this use case.

**Comment by adohertyTS** [comment]
@elifipekuysal , because the SDK already can accept arbitrary additional parameters to put in the request body, I don't think it's necessary to change the SDK just so that people can use sender IDs.

The following sample code, on lines 14-15, demonstrates how you would add a sender ID to a request using this SDK:
https://github.com/TeleSign/sample_code/blob/master/node/sdk/sms/send_sms.js

I will close this out for now, but let me know if you have want to discuss this further or are having any further trouble using sender IDs with the SDK.

**Pull request closed without merging**
